# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Last commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build files with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build
    - name: Add files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f dist/webpage.json
    - name: Commit changes
      id: can_commit
      run: |-
       commit_result=$(git commit -m "Add changes to dist and docs" -a | tr -d '\n' || true)
       echo "::set-output name=commit_result::$commit_result"
    - name: Nothing to commit
      id: nothing_committed
      if: contains(steps.can_commit.outputs.commit_result, 'nothing to commit')
      run: echo "No changes found (for both main code and docs). Skipping push."
    - name: Push changes
      if: contains(steps.can_commit.outputs.commit_result, 'nothing to commit') == false 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
